import * as p from "@clack/prompts";
import { registry } from "@premierstudio/ai-hooks/adapters";
import { askConfirm } from "../ui/prompts.js";
import { clearAuth, getAuthFilePath, loadAuth } from "../auth/token-store.js";
import { removeMcpEntry } from "../config/mcp-config.js";
import { removeConfig } from "../config/ai-hooks-config.js";

export async function removeCommand(): Promise<void> {
  p.intro("Plannable — Remove");

  const confirmed = await askConfirm("Remove all Plannable configuration from this project?");

  if (!confirmed) {
    p.outro("Nothing removed.");
    return;
  }

  const spin = p.spinner();
  spin.start("Removing Plannable configuration...");

  const removed: string[] = [];

  // Remove MCP entries from all detected tools (both scopes)
  const detected = await registry.detectAll();
  for (const adapter of detected) {
    for (const scope of ["project", "global"] as const) {
      try {
        const didRemove = await removeMcpEntry(adapter, scope);
        if (didRemove) {
          removed.push(`MCP entry from ${adapter.name} (${scope})`);
        }
      } catch {
        // Skip if removal fails
      }
    }

    // Uninstall ai-hooks configs
    try {
      await adapter.uninstall();
      removed.push(`ai-hooks config for ${adapter.name}`);
    } catch {
      // Skip if uninstall fails
    }
  }

  // Remove ai-hooks.config.ts if generated by us
  const configRemoved = await removeConfig();
  if (configRemoved) {
    removed.push("ai-hooks.config.ts");
  }

  // Clear stored auth
  const auth = await loadAuth();
  if (auth) {
    await clearAuth();
    removed.push(getAuthFilePath());
  }

  spin.stop("Removal complete");

  if (removed.length > 0) {
    p.log.success("Removed:");
    for (const item of removed) {
      p.log.info(`  - ${item}`);
    }
  } else {
    p.log.info("No Plannable configuration found to remove.");
  }

  p.outro("Plannable has been removed from this project.");
}
