import { readFile, writeFile, rm } from "node:fs/promises";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { generateHooksSource } from "./hooks-generator.js";
import type { FeatureToggles } from "../ui/prompts.js";

const CONFIG_FILENAME = "ai-hooks.config.ts";
const MARKER_COMMENT = "// Generated by plannable";

export function generateConfigSource(language: string, features: FeatureToggles): string {
  const hooksSource = generateHooksSource(language, features);

  return `${MARKER_COMMENT}
// Do not edit manually — re-run \`npx plannable setup\` to regenerate.

import { defineConfig, hook, builtinHooks } from "@premierstudio/ai-hooks";

export default defineConfig({
  extends: [{ hooks: builtinHooks }],

  hooks: [
    ${hooksSource},
  ],

  settings: {
    logLevel: "warn",
    hookTimeout: 5000,
    failMode: "open",
  },
});
`;
}

export async function writeConfig(
  language: string,
  features: FeatureToggles,
  cwd: string = process.cwd(),
): Promise<string> {
  const configPath = resolve(cwd, CONFIG_FILENAME);
  const source = generateConfigSource(language, features);
  await writeFile(configPath, source, "utf-8");
  return configPath;
}

export async function removeConfig(cwd: string = process.cwd()): Promise<boolean> {
  const configPath = resolve(cwd, CONFIG_FILENAME);
  if (!existsSync(configPath)) return false;

  try {
    const content = await readFile(configPath, "utf-8");
    if (!content.includes(MARKER_COMMENT)) {
      return false; // Not generated by us, don't remove
    }
    await rm(configPath);
    return true;
  } catch {
    return false;
  }
}

export function hasPlannableConfig(cwd: string = process.cwd()): boolean {
  const configPath = resolve(cwd, CONFIG_FILENAME);
  if (!existsSync(configPath)) return false;

  try {
    const content = readFileSync(configPath, "utf-8");
    return content.includes(MARKER_COMMENT);
  } catch {
    return false;
  }
}
