#!/usr/bin/env node
/**
 * ai-hooks runner for Gemini CLI (AfterShell).
 * Generated by: ai-hooks generate
 */
import { loadConfig, HookEngine } from "@premierstudio/ai-hooks";

const input = JSON.parse(process.env.GEMINI_HOOK_INPUT ?? "{}");

async function run() {
  const config = await loadConfig();
  const engine = new HookEngine(config);
  const toolInfo = { name: "gemini-cli", version: "1.0" };
  const timestamp = Date.now();
  const metadata = {};

  let event;
  switch ("AfterShell") {
    case "SessionStart":
      event = { type: "session:start", tool: "gemini-cli", version: "1.0", workingDirectory: process.cwd(), timestamp, metadata };
      break;
    case "BeforeShell":
      event = { type: "shell:before", command: input.command ?? "", cwd: process.cwd(), timestamp, metadata };
      break;
    case "BeforeTool":
      event = { type: "tool:before", toolName: input.toolName ?? "unknown", input, timestamp, metadata };
      break;
    case "BeforePrompt":
      event = { type: "prompt:submit", prompt: input.prompt ?? "", timestamp, metadata };
      break;
    default:
      event = { type: "tool:after", toolName: "AfterShell", input, output: {}, duration: 0, timestamp, metadata };
  }

  const results = await engine.emit(event, toolInfo);
  const blocked = results.find((r) => r.blocked);

  if (blocked) {
    console.log(JSON.stringify({ blocked: true, reason: blocked.reason }));
    process.exit(1);
  }
}

run().catch(() => process.exit(1));
