import { existsSync } from "node:fs";
import { registry, BaseAdapter } from "./index.js";
import { resolve } from "node:path";
import type {
  AdapterCapabilities,
  GeneratedConfig,
  HookDefinition,
  HookEventType,
} from "../types/index.js";

/**
 * Event mapping: ai-hooks universal events -> Codex native hooks.
 *
 * Codex supports lifecycle hooks through `.codex/hooks.json` with events like:
 *   SessionStart, UserPromptSubmit, PreToolUse, PostToolUse, Stop
 *
 * Reference: https://developers.openai.com/codex/hooks
 */
const EVENT_MAP: Record<string, string[]> = {
  "session:start": ["SessionStart"],
  "session:end": ["Stop"],
  "prompt:submit": ["UserPromptSubmit"],
  "prompt:response": ["Stop"],
  "tool:before": ["PreToolUse"],
  "tool:after": ["PostToolUse"],
  "file:read": ["PreToolUse"],
  "file:write": ["PreToolUse"],
  "file:edit": ["PreToolUse"],
  "file:delete": ["PreToolUse"],
  "shell:before": ["PreToolUse"],
  "shell:after": ["PostToolUse"],
  "mcp:before": ["PreToolUse"],
  "mcp:after": ["PostToolUse"],
};

const REVERSE_MAP: Record<string, HookEventType[]> = {
  SessionStart: ["session:start"],
  UserPromptSubmit: ["prompt:submit"],
  PreToolUse: [
    "tool:before",
    "file:read",
    "file:write",
    "file:edit",
    "file:delete",
    "shell:before",
    "mcp:before",
  ],
  PostToolUse: ["tool:after", "shell:after", "mcp:after"],
  Stop: ["session:end", "prompt:response"],
};

class CodexAdapter extends BaseAdapter {
  readonly id = "codex";
  readonly name = "Codex";
  readonly version = "1.0";

  readonly capabilities: AdapterCapabilities = {
    beforeHooks: true,
    afterHooks: true,
    mcp: true,
    configFile: true,
    supportedEvents: [
      "session:start",
      "session:end",
      "prompt:submit",
      "prompt:response",
      "tool:before",
      "tool:after",
      "file:read",
      "file:write",
      "file:edit",
      "file:delete",
      "shell:before",
      "shell:after",
      "mcp:before",
      "mcp:after",
    ],
    blockableEvents: [
      "prompt:submit",
      "tool:before",
      "file:read",
      "file:write",
      "file:edit",
      "file:delete",
      "shell:before",
      "mcp:before",
    ],
  };

  async detect(): Promise<boolean> {
    const hasCommand = await this.commandExists("codex");
    const hasDir = existsSync(resolve(process.cwd(), ".codex"));
    return hasCommand || hasDir;
  }

  async generate(hooks: HookDefinition[]): Promise<GeneratedConfig[]> {
    const configs: GeneratedConfig[] = [];

    const neededEvents = new Set<string>();
    for (const hook of hooks) {
      for (const event of hook.events) {
        const nativeEvents = this.mapEvent(event);
        for (const nativeEvent of nativeEvents) {
          neededEvents.add(nativeEvent);
        }
      }
    }

    configs.push({
      path: ".codex/hooks/ai-tools-hooks-runner.js",
      content: this.generateRunner(),
      format: "js",
    });

    const hooksConfig: Record<string, unknown[]> = {};
    for (const event of neededEvents) {
      if (!hooksConfig[event]) {
        hooksConfig[event] = [];
      }
      hooksConfig[event].push({
        hooks: [
          {
            type: "command",
            command: `node ${resolve(process.cwd(), ".codex/hooks/ai-tools-hooks-runner.js")} ${event}`,
            timeout: 10,
            statusMessage: `ai-hooks ${event}`,
          },
        ],
      });
    }

    configs.push({
      path: ".codex/hooks.json",
      content: JSON.stringify({ hooks: hooksConfig }, null, 2) + "\n",
      format: "json",
    });

    return configs;
  }

  mapEvent(event: HookEventType): string[] {
    return EVENT_MAP[event] ?? [];
  }

  mapNativeEvent(nativeEvent: string): HookEventType[] {
    return REVERSE_MAP[nativeEvent] ?? [];
  }

  async uninstall(): Promise<void> {
    await this.removeFile(".codex/hooks/ai-hooks-runner.js");
    await this.removeFile(".codex/hooks/ai-tools-hooks-runner.js");
    await this.removeFile(".codex/hooks.json");
  }

  private generateRunner(): string {
    return `#!/usr/bin/env node
/**
 * ai-hooks runner for Codex.
 * Generated by: ai-hooks generate
 *
 * Codex passes hook event data as JSON via STDIN. PreToolUse and
 * UserPromptSubmit can block execution via exit code 2 + stderr.
 *
 * DO NOT EDIT - regenerate with: ai-hooks generate
 */
import { loadConfig, HookEngine } from "@premierstudio/ai-tools-hooks";

const PROJECT_ROOT = "${resolve(process.cwd())}";
process.chdir(PROJECT_ROOT);

async function readStdin() {
  const chunks = [];
  for await (const chunk of process.stdin) {
    chunks.push(chunk);
  }
  return Buffer.concat(chunks).toString("utf-8");
}

function getMcpIdentity(toolName) {
  if (!toolName.startsWith("mcp__")) {
    return null;
  }
  const parts = toolName.split("__");
  return {
    server: parts[1] ?? "unknown",
    method: toolName,
  };
}

function resolvePreToolUse(toolName, toolInput, timestamp, metadata) {
  const mcp = getMcpIdentity(toolName);
  if (mcp) {
    return {
      type: "mcp:before",
      server: mcp.server,
      method: mcp.method,
      params: toolInput,
      timestamp,
      metadata,
    };
  }

  switch (toolName) {
    case "Bash":
      return {
        type: "shell:before",
        command: toolInput.command ?? "",
        cwd: toolInput.cwd ?? process.cwd(),
        timestamp,
        metadata,
      };
    case "Read":
      return {
        type: "file:read",
        path: toolInput.file_path ?? toolInput.path ?? "",
        timestamp,
        metadata,
      };
    case "Write":
      return {
        type: "file:write",
        path: toolInput.file_path ?? toolInput.path ?? "",
        content: toolInput.content ?? "",
        timestamp,
        metadata,
      };
    case "Edit":
    case "apply_patch":
      return {
        type: "file:edit",
        path: toolInput.file_path ?? toolInput.path ?? "",
        oldContent: toolInput.old_string ?? toolInput.oldContent ?? toolInput.old ?? "",
        newContent: toolInput.new_string ?? toolInput.newContent ?? toolInput.new ?? toolInput.command ?? "",
        timestamp,
        metadata,
      };
    default:
      return {
        type: "tool:before",
        toolName: toolName || "unknown",
        input: toolInput,
        timestamp,
        metadata,
      };
  }
}

function resolvePostToolUse(toolName, toolInput, toolResponse, timestamp, metadata) {
  const mcp = getMcpIdentity(toolName);
  if (mcp) {
    return {
      type: "mcp:after",
      server: mcp.server,
      method: mcp.method,
      params: toolInput,
      result: toolResponse,
      duration: 0,
      timestamp,
      metadata,
    };
  }

  switch (toolName) {
    case "Bash":
      return {
        type: "shell:after",
        command: toolInput.command ?? "",
        cwd: toolInput.cwd ?? process.cwd(),
        exitCode: toolResponse.exitCode ?? 0,
        stdout: toolResponse.stdout ?? "",
        stderr: toolResponse.stderr ?? "",
        duration: 0,
        timestamp,
        metadata,
      };
    default:
      return {
        type: "tool:after",
        toolName: toolName || "unknown",
        input: toolInput,
        output: toolResponse,
        duration: 0,
        timestamp,
        metadata,
      };
  }
}

function buildEvents(hookEventName, input, timestamp, metadata) {
  switch (hookEventName) {
    case "SessionStart":
      return [
        {
          type: "session:start",
          tool: "codex",
          version: "1.0",
          workingDirectory: input.cwd ?? process.cwd(),
          timestamp,
          metadata,
        },
      ];
    case "UserPromptSubmit":
      return [
        {
          type: "prompt:submit",
          prompt: input.prompt ?? "",
          timestamp,
          metadata,
        },
      ];
    case "PreToolUse":
      return [resolvePreToolUse(input.tool_name ?? "", input.tool_input ?? {}, timestamp, metadata)];
    case "PostToolUse":
      return [
        resolvePostToolUse(
          input.tool_name ?? "",
          input.tool_input ?? {},
          input.tool_response ?? {},
          timestamp,
          metadata,
        ),
      ];
    case "Stop": {
      const events = [];
      if (typeof input.last_assistant_message === "string" && input.last_assistant_message.length > 0) {
        events.push({
          type: "prompt:response",
          response: input.last_assistant_message,
          model: input.model ?? "codex",
          tokens: { input: 0, output: 0 },
          timestamp,
          metadata,
        });
      }
      events.push({
        type: "session:end",
        tool: "codex",
        duration: 0,
        timestamp,
        metadata,
      });
      return events;
    }
    default:
      return [];
  }
}

async function run() {
  let input = {};
  try {
    const raw = await readStdin();
    input = JSON.parse(raw || "{}");
  } catch {
    input = {};
  }

  const hookEventName = process.argv[2] ?? "";
  const config = await loadConfig();
  const engine = new HookEngine(config);
  const toolInfo = { name: "codex", version: "1.0" };
  const timestamp = Date.now();
  const metadata = {};

  const events = buildEvents(hookEventName, input, timestamp, metadata);
  if (!events.length) {
    process.exit(0);
  }

  const results = [];
  for (const event of events) {
    const emitted = await engine.emit(event, toolInfo);
    results.push(...emitted);
  }

  const blocked = results.find((result) => result.blocked);
  if (blocked && (hookEventName === "PreToolUse" || hookEventName === "UserPromptSubmit")) {
    process.stderr.write(blocked.reason ?? "Blocked by ai-hooks");
    process.exit(2);
  }
}

run().catch((err) => {
  console.error("[ai-hooks] Error:", err.message);
  process.exit(1);
});
`;
  }
}

const adapter = new CodexAdapter();
registry.register(adapter);

export { CodexAdapter };
export default adapter;
