import { existsSync } from "node:fs";
import { readdir, readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { BaseAdapter, registry } from "./index.js";
import { collectNativeEvents, parseHookGroups, type NativeHookGroup } from "./claude-compat.js";
import type {
  AdapterCapabilities,
  GeneratedConfig,
  HookDefinition,
  HookEventType,
} from "../types/index.js";

/**
 * Event mapping: ai-hooks universal events -> Grok native hooks.
 * Grok's JSON format is Claude-compatible and is loaded from
 * `<project>/.grok/hooks/*.json` (and `~/.grok/hooks/*.json`).
 */
const EVENT_MAP: Record<string, string[]> = {
  "session:start": ["SessionStart"],
  "session:end": ["SessionEnd"],
  "prompt:submit": ["UserPromptSubmit"],
  "prompt:response": [],
  "tool:before": ["PreToolUse"],
  "tool:after": ["PostToolUse"],
  "file:read": ["PreToolUse"],
  "file:write": ["PreToolUse"],
  "file:edit": ["PreToolUse"],
  "file:delete": ["PreToolUse"],
  "shell:before": ["PreToolUse"],
  "shell:after": ["PostToolUse"],
  "mcp:before": ["PreToolUse"],
  "mcp:after": ["PostToolUse"],
  notification: ["Notification"],
};

const REVERSE_MAP: Record<string, HookEventType[]> = {
  SessionStart: ["session:start"],
  SessionEnd: ["session:end"],
  UserPromptSubmit: ["prompt:submit"],
  PreToolUse: [
    "tool:before",
    "file:read",
    "file:write",
    "file:edit",
    "file:delete",
    "shell:before",
    "mcp:before",
  ],
  PostToolUse: ["tool:after", "shell:after", "mcp:after"],
  Notification: ["notification"],
};

const HOOKS_JSON = ".grok/hooks/ai-tools.json";
const RUNNER_JS = ".grok/hooks/ai-tools-runner.js";
const RUNNER_COMMAND = "node ai-tools-runner.js";

class GrokAdapter extends BaseAdapter {
  readonly id = "grok";
  readonly name = "Grok";
  readonly version = "1.0";

  readonly capabilities: AdapterCapabilities = {
    beforeHooks: true,
    afterHooks: true,
    mcp: true,
    configFile: true,
    supportedEvents: [
      "session:start",
      "session:end",
      "prompt:submit",
      "tool:before",
      "tool:after",
      "file:read",
      "file:write",
      "file:edit",
      "file:delete",
      "shell:before",
      "shell:after",
      "mcp:before",
      "mcp:after",
      "notification",
    ],
    blockableEvents: ["prompt:submit", "tool:before", "shell:before", "mcp:before"],
  };

  async detect(): Promise<boolean> {
    const hasCommand = await this.commandExists("grok");
    const hasDir = existsSync(resolve(process.cwd(), ".grok"));
    return hasCommand || hasDir;
  }

  async generate(hooks: HookDefinition[]): Promise<GeneratedConfig[]> {
    const nativeEvents = collectNativeEvents(hooks, (event) => this.mapEvent(event));
    const hooksTable: Record<string, NativeHookGroup[]> = {};
    for (const native of nativeEvents) {
      hooksTable[native] = [
        {
          hooks: [{ type: "command", command: RUNNER_COMMAND, timeout: 10 }],
        },
      ];
    }

    return [
      {
        path: HOOKS_JSON,
        content: `${JSON.stringify({ hooks: hooksTable }, null, 2)}\n`,
        format: "json",
      },
      {
        path: RUNNER_JS,
        content: this.generateRunner(),
        format: "js",
      },
    ];
  }

  async import(cwd?: string): Promise<HookDefinition[]> {
    const dir = cwd ?? process.cwd();
    const hooksDir = resolve(dir, ".grok/hooks");
    if (!existsSync(hooksDir)) return [];
    const entries = await readdir(hooksDir);
    const imported: HookDefinition[] = [];
    for (const entry of entries) {
      if (!entry.endsWith(".json")) continue;
      const fullPath = resolve(hooksDir, entry);
      let parsed: { hooks?: Record<string, unknown> };
      try {
        parsed = JSON.parse(await readFile(fullPath, "utf-8")) as {
          hooks?: Record<string, unknown>;
        };
      } catch {
        continue;
      }
      for (const [nativeEvent, groups] of Object.entries(parsed.hooks ?? {})) {
        imported.push(
          ...parseHookGroups(groups, nativeEvent, (event) => this.mapNativeEvent(event), "grok"),
        );
      }
    }
    return imported;
  }

  mapEvent(event: HookEventType): string[] {
    return EVENT_MAP[event] ?? [];
  }

  mapNativeEvent(nativeEvent: string): HookEventType[] {
    return REVERSE_MAP[nativeEvent] ?? [];
  }

  async uninstall(): Promise<void> {
    await this.removeFile(HOOKS_JSON);
    await this.removeFile(RUNNER_JS);
  }

  private generateRunner(): string {
    return `#!/usr/bin/env node
/**
 * ai-hooks runner for Grok.
 * Generated by: ai-hooks generate
 *
 * Grok sends the event as JSON on stdin (GROK_HOOK_EVENT is also set).
 * PreToolUse / UserPromptSubmit can block via {"decision":"deny"} on stdout.
 *
 * DO NOT EDIT - regenerate with: ai-hooks generate
 */
import { runGrokHook } from "@itz4blitz/ai-tools-hooks";

const PROJECT_ROOT = ${JSON.stringify(resolve(process.cwd()))};
process.chdir(PROJECT_ROOT);

process.exit(await runGrokHook());
`;
  }
}

const adapter = new GrokAdapter();
registry.register(adapter);
export { GrokAdapter };
export default adapter;
