import { BaseAdapter, registry } from "./index.js";
import type {
  AdapterCapabilities,
  GeneratedConfig,
  HookDefinition,
  HookEventType,
} from "../types/index.js";
import { existsSync } from "node:fs";
import { resolve } from "node:path";

/**
 * Event mapping: ai-hooks -> Codex CLI native hooks.
 *
 * Codex uses an `agents.yaml` config with lifecycle events.
 * Reference: https://github.com/openai/codex
 */
const EVENT_MAP: Record<string, string[]> = {
  "session:start": ["session_start"],
  "session:end": ["session_end"],
  "prompt:submit": ["user_message"],
  "prompt:response": ["assistant_message"],
  "tool:before": ["before_tool_call"],
  "tool:after": ["after_tool_call"],
  "file:write": ["before_file_write"],
  "file:edit": ["before_file_edit"],
  "file:delete": ["before_file_delete"],
  "shell:before": ["before_shell"],
  "shell:after": ["after_shell"],
  "mcp:before": ["before_mcp_call"],
  "mcp:after": ["after_mcp_call"],
};

const REVERSE_MAP: Record<string, HookEventType[]> = {
  session_start: ["session:start"],
  session_end: ["session:end"],
  user_message: ["prompt:submit"],
  assistant_message: ["prompt:response"],
  before_tool_call: ["tool:before"],
  after_tool_call: ["tool:after"],
  before_file_write: ["file:write"],
  before_file_edit: ["file:edit"],
  before_file_delete: ["file:delete"],
  before_shell: ["shell:before"],
  after_shell: ["shell:after"],
  before_mcp_call: ["mcp:before"],
  after_mcp_call: ["mcp:after"],
};

class CodexAdapter extends BaseAdapter {
  readonly id = "codex";
  readonly name = "Codex CLI";
  readonly version = "1.0";

  readonly capabilities: AdapterCapabilities = {
    beforeHooks: true,
    afterHooks: true,
    mcp: true,
    configFile: true,
    supportedEvents: [
      "session:start",
      "session:end",
      "prompt:submit",
      "prompt:response",
      "tool:before",
      "tool:after",
      "file:write",
      "file:edit",
      "file:delete",
      "shell:before",
      "shell:after",
      "mcp:before",
      "mcp:after",
    ],
    blockableEvents: [
      "tool:before",
      "file:write",
      "file:edit",
      "file:delete",
      "shell:before",
      "mcp:before",
    ],
  };

  async detect(): Promise<boolean> {
    const hasCommand = await this.commandExists("codex");
    const hasConfig =
      existsSync(resolve(process.cwd(), "codex.json")) ||
      existsSync(resolve(process.cwd(), ".codex"));
    return hasCommand || hasConfig;
  }

  async generate(hooks: HookDefinition[]): Promise<GeneratedConfig[]> {
    // Codex uses a codex.json config file with hooks array
    const hookEntries: Record<string, unknown> = {};

    for (const hook of hooks) {
      for (const event of hook.events) {
        const nativeEvents = this.mapEvent(event);
        for (const ne of nativeEvents) {
          hookEntries[ne] = {
            command: "node .codex/hooks/ai-hooks-runner.js",
            timeout: 10,
          };
        }
      }
    }

    return [
      {
        path: ".codex/hooks/ai-hooks-runner.js",
        content: this.generateRunner(),
        format: "js",
      },
      {
        path: "codex.json",
        content: JSON.stringify({ hooks: hookEntries }, null, 2) + "\n",
        format: "json",
      },
    ];
  }

  mapEvent(event: HookEventType): string[] {
    return EVENT_MAP[event] ?? [];
  }

  mapNativeEvent(nativeEvent: string): HookEventType[] {
    return REVERSE_MAP[nativeEvent] ?? [];
  }

  async uninstall(): Promise<void> {
    await this.removeFile(".codex/hooks/ai-hooks-runner.js");
  }

  private generateRunner(): string {
    return `#!/usr/bin/env node
/**
 * ai-hooks runner for Codex CLI.
 * Generated by: ai-hooks generate
 */
import { loadConfig, HookEngine } from "@premierstudio/ai-hooks";

const hookEvent = process.env.CODEX_HOOK_EVENT;
const toolInput = process.env.CODEX_TOOL_INPUT;

async function run() {
  const config = await loadConfig();
  const engine = new HookEngine(config);
  const toolInfo = { name: "codex", version: "1.0" };

  const input = toolInput ? JSON.parse(toolInput) : {};
  const timestamp = Date.now();
  const metadata = {};

  let event;
  switch (hookEvent) {
    case "before_shell":
      event = { type: "shell:before", command: input.command ?? "", cwd: process.cwd(), timestamp, metadata };
      break;
    case "before_file_write":
      event = { type: "file:write", path: input.path ?? "", content: input.content ?? "", timestamp, metadata };
      break;
    case "before_file_edit":
      event = { type: "file:edit", path: input.path ?? "", oldContent: input.old ?? "", newContent: input.new ?? "", timestamp, metadata };
      break;
    default:
      event = { type: "tool:before", toolName: hookEvent ?? "unknown", input, timestamp, metadata };
  }

  const results = await engine.emit(event, toolInfo);
  const blocked = results.find((r) => r.blocked);

  if (blocked) {
    console.log(JSON.stringify({ blocked: true, reason: blocked.reason }));
    process.exit(1);
  }
}

run().catch(() => process.exit(1));
`;
  }
}

const adapter = new CodexAdapter();
registry.register(adapter);

export { CodexAdapter };
export default adapter;
