import { BaseAdapter, registry } from "./index.js";
import type {
  AdapterCapabilities,
  GeneratedConfig,
  HookDefinition,
  HookEventType,
} from "../types/index.js";
import { existsSync } from "node:fs";
import { resolve } from "node:path";

/**
 * Event mapping: ai-hooks universal events -> Kiro CLI native hooks.
 *
 * Kiro supports five hook types:
 *   agentSpawn, userPromptSubmit, preToolUse, postToolUse, stop
 *
 * Reference: https://kiro.dev/docs/cli/hooks/
 */
const EVENT_MAP: Record<string, string[]> = {
  "session:start": ["agentSpawn"],
  "session:end": ["stop"],
  "prompt:submit": ["userPromptSubmit"],
  "prompt:response": ["stop"],
  "tool:before": ["preToolUse"],
  "tool:after": ["postToolUse"],
  "file:read": ["preToolUse"],
  "file:write": ["preToolUse"],
  "file:edit": ["preToolUse"],
  "file:delete": ["preToolUse"],
  "shell:before": ["preToolUse"],
  "shell:after": ["postToolUse"],
  "mcp:before": ["preToolUse"],
  "mcp:after": ["postToolUse"],
};

const REVERSE_MAP: Record<string, HookEventType[]> = {
  agentSpawn: ["session:start"],
  userPromptSubmit: ["prompt:submit"],
  preToolUse: [
    "tool:before",
    "file:read",
    "file:write",
    "file:edit",
    "file:delete",
    "shell:before",
    "mcp:before",
  ],
  postToolUse: ["tool:after", "shell:after", "mcp:after"],
  stop: ["session:end", "prompt:response"],
};

/**
 * Kiro CLI adapter for ai-hooks.
 *
 * Generates hook entries for Kiro's agent configuration format. Kiro uses
 * JSON agent config files in `.kiro/` with a `hooks` section containing
 * agentSpawn, userPromptSubmit, preToolUse, postToolUse, and stop events.
 *
 * Hook scripts receive event data as JSON via STDIN. Exit code 2 blocks
 * execution on preToolUse hooks.
 *
 * Reference: https://kiro.dev/docs/cli/hooks/
 */
class KiroAdapter extends BaseAdapter {
  readonly id = "kiro";
  readonly name = "Kiro CLI";
  readonly version = "1.0";

  readonly capabilities: AdapterCapabilities = {
    beforeHooks: true,
    afterHooks: true,
    mcp: true,
    configFile: true,
    supportedEvents: [
      "session:start",
      "session:end",
      "prompt:submit",
      "prompt:response",
      "tool:before",
      "tool:after",
      "file:read",
      "file:write",
      "file:edit",
      "file:delete",
      "shell:before",
      "shell:after",
      "mcp:before",
      "mcp:after",
    ],
    blockableEvents: [
      "tool:before",
      "file:read",
      "file:write",
      "file:edit",
      "file:delete",
      "shell:before",
      "mcp:before",
    ],
  };

  async detect(): Promise<boolean> {
    const hasCommand = await this.commandExists("kiro");
    const hasDir = existsSync(resolve(process.cwd(), ".kiro"));
    return hasCommand || hasDir;
  }

  async generate(hooks: HookDefinition[]): Promise<GeneratedConfig[]> {
    const configs: GeneratedConfig[] = [];

    // Collect needed native events
    const neededEvents = new Set<string>();
    for (const hook of hooks) {
      for (const event of hook.events) {
        const nativeEvents = this.mapEvent(event);
        for (const ne of nativeEvents) {
          neededEvents.add(ne);
        }
      }
    }

    // Generate the runner script
    configs.push({
      path: ".kiro/hooks/ai-hooks-runner.js",
      content: this.generateRunner(),
      format: "js",
    });

    // Build Kiro hooks config
    const hooksConfig: Record<string, unknown[]> = {};

    for (const event of neededEvents) {
      const entry: Record<string, unknown> = {
        command: "node .kiro/hooks/ai-hooks-runner.js",
      };

      // preToolUse and postToolUse support matchers; use wildcard
      if (event === "preToolUse" || event === "postToolUse") {
        entry.matcher = "*";
      }

      if (!hooksConfig[event]) {
        hooksConfig[event] = [];
      }
      hooksConfig[event].push(entry);
    }

    configs.push({
      path: ".kiro/hooks/ai-hooks.json",
      content: JSON.stringify({ hooks: hooksConfig }, null, 2) + "\n",
      format: "json",
    });

    return configs;
  }

  mapEvent(event: HookEventType): string[] {
    return EVENT_MAP[event] ?? [];
  }

  mapNativeEvent(nativeEvent: string): HookEventType[] {
    return REVERSE_MAP[nativeEvent] ?? [];
  }

  async uninstall(): Promise<void> {
    await this.removeFile(".kiro/hooks/ai-hooks-runner.js");
    await this.removeFile(".kiro/hooks/ai-hooks.json");
  }

  private generateRunner(): string {
    return `#!/usr/bin/env node
/**
 * ai-hooks runner for Kiro CLI.
 * Generated by: ai-hooks generate
 *
 * Kiro passes hook event data as JSON via STDIN.
 * Exit code 0 = success, exit code 2 = block (preToolUse only).
 *
 * DO NOT EDIT - regenerate with: ai-hooks generate
 */
import { loadConfig, HookEngine } from "@premierstudio/ai-hooks";

async function readStdin() {
  const chunks = [];
  for await (const chunk of process.stdin) {
    chunks.push(chunk);
  }
  return Buffer.concat(chunks).toString("utf-8");
}

async function run() {
  const raw = await readStdin();
  const input = JSON.parse(raw || "{}");
  const hookEventName = input.hook_event_name ?? "";
  const toolName = input.tool_name ?? "";
  const toolInput = input.tool_input ?? {};

  const config = await loadConfig();
  const engine = new HookEngine(config);
  const toolInfo = { name: "kiro", version: "1.0" };
  const timestamp = Date.now();
  const metadata = {};

  let event;
  switch (hookEventName) {
    case "agentSpawn":
      event = {
        type: "session:start",
        tool: "kiro",
        version: "1.0",
        workingDirectory: input.cwd ?? process.cwd(),
        timestamp,
        metadata,
      };
      break;
    case "userPromptSubmit":
      event = {
        type: "prompt:submit",
        prompt: toolInput.prompt ?? "",
        timestamp,
        metadata,
      };
      break;
    case "preToolUse":
      event = resolvePreToolEvent(toolName, toolInput, timestamp, metadata);
      break;
    case "postToolUse":
      event = resolvePostToolEvent(toolName, toolInput, input.tool_response ?? {}, timestamp, metadata);
      break;
    case "stop":
      event = {
        type: "session:end",
        tool: "kiro",
        duration: 0,
        timestamp,
        metadata,
      };
      break;
    default:
      process.exit(0);
  }

  const results = await engine.emit(event, toolInfo);
  const blocked = results.find((r) => r.blocked);

  if (blocked) {
    process.stderr.write(blocked.reason ?? "Blocked by ai-hooks");
    process.exit(2);
  }
}

function resolvePreToolEvent(toolName, toolInput, timestamp, metadata) {
  switch (toolName) {
    case "fs_write":
    case "write":
      return { type: "file:write", path: toolInput.path ?? "", content: toolInput.content ?? "", timestamp, metadata };
    case "fs_edit":
    case "edit":
      return { type: "file:edit", path: toolInput.path ?? "", oldContent: toolInput.old_string ?? "", newContent: toolInput.new_string ?? "", timestamp, metadata };
    case "fs_read":
    case "read":
      return { type: "file:read", path: toolInput.path ?? "", timestamp, metadata };
    case "execute_bash":
    case "shell":
      return { type: "shell:before", command: toolInput.command ?? "", cwd: process.cwd(), timestamp, metadata };
    default:
      return { type: "tool:before", toolName: toolName || "unknown", input: toolInput, timestamp, metadata };
  }
}

function resolvePostToolEvent(toolName, toolInput, toolResponse, timestamp, metadata) {
  switch (toolName) {
    case "execute_bash":
    case "shell":
      return {
        type: "shell:after",
        command: toolInput.command ?? "",
        cwd: process.cwd(),
        exitCode: toolResponse.exitCode ?? 0,
        stdout: toolResponse.stdout ?? "",
        stderr: toolResponse.stderr ?? "",
        duration: 0,
        timestamp,
        metadata,
      };
    default:
      return { type: "tool:after", toolName: toolName || "unknown", input: toolInput, output: toolResponse, duration: 0, timestamp, metadata };
  }
}

run().catch((err) => {
  console.error("[ai-hooks] Error:", err.message);
  process.exit(1);
});
`;
  }
}

// Auto-register
const adapter = new KiroAdapter();
registry.register(adapter);

export { KiroAdapter };
export default adapter;
